In [ ]:
#we are going to construct three models
#1st model is one without principal component analysis
import pandas as pd

df = pd.read_csv("Fundraising.csv")

In [ ]:
df.describe(include="all")

zipcode  homeowner dummy      NUMCHLD  gender dummy       WEALTH  \
count  3120.000000      3120.000000  3120.000000   3120.000000  3120.000000   
mean      3.766667         0.770192     1.069231      0.609295     6.402244   
std       1.176904         0.420777     0.347688      0.487987     2.539978   
min       1.000000         0.000000     1.000000      0.000000     0.000000   
25%       3.000000         1.000000     1.000000      0.000000     5.000000   
50%       4.000000         1.000000     1.000000      1.000000     8.000000   
75%       5.000000         1.000000     1.000000      1.000000     8.000000   
max       5.000000         1.000000     5.000000      1.000000     9.000000   

                HV        Icmed        Icavg      NUMPROM     MAXRAMNT  \
count  3120.000000  3120.000000  3120.000000  3120.000000  3120.000000   
mean   1141.361859   388.217308   432.088141    49.089423    16.651397   
std     946.642162   172.815950   168.195104    22.717130    22.223521   
min       0.000000     0.000000     0.000000    11.000000     5.000000   
25%     556.000000   278.000000   318.000000    29.000000    10.000000   
50%     822.000000   356.000000   396.000000    48.000000    15.000000   
75%    1338.750000   465.000000   516.000000    65.000000    20.000000   
max    5945.000000  1500.000000  1331.000000   157.000000  1000.000000   

       totalmonths        Donor  
count  3120.000000  3120.000000  
mean     31.136859     0.383654  
std       4.132952     0.486353  
min      17.000000     0.000000  
25%      29.000000     0.000000  
50%      31.000000     0.000000  
75%      34.000000     1.000000  
max      37.000000     1.000000

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3120 entries, 0 to 3119
Data columns (total 12 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   zipcode          3120 non-null   int64  
 1   homeowner dummy  3120 non-null   int64  
 2   NUMCHLD          3120 non-null   int64  
 3   gender dummy     3120 non-null   int64  
 4   WEALTH           3120 non-null   int64  
 5   HV               3120 non-null   int64  
 6   Icmed            3120 non-null   int64  
 7   Icavg            3120 non-null   int64  
 8   NUMPROM          3120 non-null   int64  
 9   MAXRAMNT         3120 non-null   float64
 10  totalmonths      3120 non-null   int64  
 11  Donor            3120 non-null   int64  
dtypes: float64(1), int64(11)
memory usage: 292.6 KB


In [ ]:
x = df.iloc[:,0:11]  #column location ..........all rows
y = df['Donor']

In [ ]:
#preprocess ind variable dataframe x by standardizing it
from sklearn.preprocessing import StandardScaler
x = StandardScaler().fit_transform(x)

In [ ]:
#first model is logistic regression w/o any pca
from sklearn.model_selection import train_test_split
x_train, x_val, y_train, y_val = train_test_split(x,y, test_size=0.3,
                                                  random_state=0)

In [ ]:
# Model 1: A simple logistic regressino model without PCA
from sklearn.linear_model import LogisticRegression
model1 = LogisticRegression()
model1.fit(x_train,y_train)
# Evaluating accuracy
model1.score(x_val,y_val)



0.6677350427350427

In [ ]:
#MODEL 2
#Apply PCA to the entire independent variables(11)......we have 11 PC
#How do we run PC
# Model 2: Logistic regression with PCA
# Model 2: PCA is applied to all independent variables
from sklearn.decomposition import PCA
pca = PCA()
PCA_v1 = pca.fit_transform(x) #first version of PC #we fit model with all ind var
print(PCA_v1[0,:])      #first row

[ 1.85357544  0.77740602 -1.11342648 -0.57636915  0.70724986  0.447121
 -1.1719957  -0.48479383  0.88129526 -0.41904927 -0.13945821]


In [ ]:
#All org ind var now become PC1........11
#i.e 11 org ind var are now represented by 11PC


In [ ]:
# Check variances explained by each principal components
pca.explained_variance_ratio_
#explained_variance_ratio_ IS proportion of variance explained
#1st PC captures 27%of info


array([0.26993694, 0.13296439, 0.09755934, 0.09314764, 0.08973188,
       0.08819136, 0.08415172, 0.07559969, 0.04144892, 0.02479158,
       0.00247653])

In [ ]:
#1st PC captured only 26.9% of info in org var........pretty bad
#why so?
#observe data1:08 in video-6
#where do you live? I might be poor living in a wealthy area
#Also not all rich people are generous
########when the data is so diverse............it is very hard to come up with a really good PC that captures all the info


In [ ]:
# Check eigenvalues of each principal components
pca.explained_variance_
#How many principle components do you want to keep for your predicted model?
#4(threshold=1)
#Instead of using original 11 ind var...with pca we can reduce dimen from 11 to 4

array([2.97025835, 1.46307725, 1.07349682, 1.0249525 , 0.98736713,
       0.97041598, 0.92596574, 0.83186322, 0.45608434, 0.27279486,
       0.02725058])

In [ ]:
# Check eigenvectors of each principal components
pca.components_
#eigenvector tells how principle component is calculated

array([[ 1.88599819e-01,  1.17824379e-01,  3.95630864e-02,
        -2.55922182e-02,  3.05520130e-01,  4.95865549e-01,
         5.42436063e-01,  5.45846038e-01, -1.17231713e-01,
         2.85404254e-02,  4.85749173e-02],
       [ 2.12015991e-01,  8.39969403e-03, -1.93860556e-01,
         1.18355250e-01, -4.15048984e-01,  1.64232593e-01,
         1.01382691e-01,  9.81517530e-02,  6.78913772e-01,
         2.22738897e-01, -4.16775765e-01],
       [ 3.93420510e-01, -3.03826675e-01, -5.71293274e-01,
         1.26578865e-01, -1.13129707e-01,  1.06434470e-01,
        -7.74372807e-02, -7.55164465e-02, -1.64011438e-01,
         3.00793477e-01,  5.07256423e-01],
       [-2.92403785e-01, -2.69636918e-01,  1.85129018e-01,
        -6.29737914e-01, -2.62507626e-02, -2.49895944e-02,
         6.73064953e-02,  6.54040727e-02,  9.88379462e-02,
         6.14089715e-01,  1.18138934e-01],
       [-2.62236187e-01, -7.30347904e-01, -1.48007301e-01,
         3.08066802e-01,  3.16362249e-01, -2.80026751e-02,
  

In [ ]:
#CREATE SECOND MODEL WITH ONLY TOP 4 PCs
# Only keep PCs with eigenvalue>=1
# Use 4 principal components to train the model
pca = PCA(n_components=4)
PCA_v1 = pca.fit_transform(x)

In [ ]:
#create model 2
# Data partition: the independent variables are just four PCs
x2_train, x2_val, y_train, y_val = train_test_split(PCA_v1,y, test_size=0.3,
                                                    random_state=0)

In [ ]:
model2 = LogisticRegression()
model2.fit(x2_train,y_train)
# Evaluating accuracy
model2.score(x2_val,y_val)

0.6613247863247863

In [ ]:
#after we run pca they become array type of data for numpy..........hce make it a dataframe
#display PCA results
pcaDf = pd.DataFrame(data = PCA_v1
             , columns = ['PC1', 'PC2','PC3','PC4'])
pcaDf.head()
#instead of zipcode and evrything..........we create 4 PCs and these are the numbers that enter the second model
#How do we come up with this value 1.85....?
#Based on Eigenvectors

PC1       PC2       PC3       PC4
0  1.853575  0.777406 -1.113426 -0.576369
1 -0.105063 -0.987419 -0.595625  1.011827
2 -0.126918 -0.945366 -0.756317 -0.182559
3  0.586538  2.080479 -0.301796  0.372627
4 -0.031337 -1.419833 -0.609570  0.475773

In [ ]:
pcaDf.describe()

PC1           PC2           PC3           PC4
count  3.120000e+03  3.120000e+03  3.120000e+03  3.120000e+03
mean   4.099285e-17  3.416071e-18 -3.871547e-17 -2.277381e-18
std    1.723444e+00  1.209577e+00  1.036097e+00  1.012399e+00
min   -4.473280e+00 -3.901788e+00 -6.921941e+00 -1.843964e+00
25%   -1.126041e+00 -8.674400e-01 -4.872367e-01 -7.039011e-01
50%   -2.930773e-01 -9.694405e-02  1.043976e-01 -1.002340e-01
75%    8.303739e-01  7.337902e-01  6.174998e-01  6.252765e-01
max    9.446558e+00  1.385844e+01  1.249673e+01  2.749703e+01

In [ ]:
# Two issues with the SECOND MODEL
#1  First PC has lesss variance
#2 Very difficult to explain the results


In [ ]:
#CREATE THIRD MODEL - apply PCA selectively
# Model 3: Logistic regression with PCA
# Model 3: PCA is applied to selected independent variables(conceptually relevant)
# Convert numpy array to a dataframe
x3 = pd.DataFrame(data = x
             , columns = ['zip', 'homeowner','child','gender','wealth','HV',
                          'icmed','icavg','num','max','totalm'])
x3.corr()

zip  homeowner     child    gender    wealth        HV  \
zip        1.000000   0.040594 -0.036512  0.024321  0.016285  0.358698   
homeowner  0.040594   1.000000  0.045229  0.002911  0.064920  0.111643   
child     -0.036512   0.045229  1.000000 -0.033273  0.061760 -0.010206   
gender     0.024321   0.002911 -0.033273  1.000000 -0.030954 -0.022055   
wealth     0.016285   0.064920  0.061760 -0.030954  1.000000  0.258350   
HV         0.358698   0.111643 -0.010206 -0.022055  0.258350  1.000000   
icmed      0.168491   0.138074  0.050766 -0.025058  0.373116  0.733773   
icavg      0.170888   0.133026  0.050905 -0.026248  0.381161  0.748237   
num       -0.005263   0.003761 -0.087367  0.033954 -0.413888 -0.062467   
max        0.021753  -0.029656 -0.017954  0.002595 -0.024830  0.055236   
totalm    -0.001211   0.025650 -0.005034 -0.036908  0.027617  0.026103   

              icmed     icavg       num       max    totalm  
zip        0.168491  0.170888 -0.005263  0.021753 -0.001211  
homeowner  0.138074  0.133026  0.003761 -0.029656  0.025650  
child      0.050766  0.050905 -0.087367 -0.017954 -0.005034  
gender    -0.025058 -0.026248  0.033954  0.002595 -0.036908  
wealth     0.373116  0.381161 -0.413888 -0.024830  0.027617  
HV         0.733773  0.748237 -0.062467  0.055236  0.026103  
icmed      1.000000  0.972409 -0.050267  0.046222  0.034636  
icavg      0.972409  1.000000 -0.056079  0.042985  0.032965  
num       -0.050267 -0.056079  1.000000  0.110307 -0.284819  
max        0.046222  0.042985  0.110307  1.000000  0.019870  
totalm     0.034636  0.032965 -0.284819  0.019870  1.000000

In [ ]:
# HV,icmed,icavg high corr
#instead of running PCA for everything, apply them selectively
#i.e apply PCA to only correlated variables

In [ ]:
# Columns without PCA
x3_no_PCA = pd.concat([x3.iloc[:,0:5], x3.iloc[:,8:11]],axis=1)
x3_no_PCA.head()
#np corr between these columns

zip  homeowner     child    gender    wealth       num       max  \
0 -0.651531   0.546239 -0.199149  0.800776  1.022912  1.096731 -0.479362   
1 -1.501355   0.546239 -0.199149 -1.248789  0.235377 -0.136017 -0.209334   
2  1.048116  -1.830701  2.677454  0.800776  0.629144 -0.752391 -0.299343   
3  1.048116   0.546239 -0.199149 -1.248789 -0.945925  1.977265 -0.299343   
4 -0.651531   0.546239 -0.199149 -1.248789  0.629144 -1.280711 -0.254339   

     totalm  
0 -0.517113  
1  0.692870  
2 -0.517113  
3 -0.275116  
4 -0.275116

In [ ]:
# Columns with PCA
x3_PCA =x3.iloc[:,5:8]
x3_PCA.head()

HV     icmed     icavg
0  0.272204  1.439813  1.610958
1 -0.468427  0.195515  0.183815
2 -0.331078 -0.174881 -0.333524
3  0.348274  0.554336  0.677369
4 -0.627964 -0.012833 -0.000524

In [ ]:
#After selecting cols run PCA
pca2 = PCA()
PCA_v2 = pca2.fit_transform(x3_PCA)

In [ ]:
# Check variances explained by each principal components
pca2.explained_variance_ratio_

array([0.88048423, 0.11040409, 0.00911168])

In [ ]:
#1st PC 88% OF INFO CAPTURED

In [ ]:
# Check eigenvalues of each principal components
pca2.explained_variance_

array([2.64229957, 0.33131846, 0.02734382])

In [ ]:
#WE NEED ONLY ONE AS EV>1

In [ ]:
# Check eigenectors of each principal components
pca2.components_

array([[ 0.53811795,  0.59450807,  0.59748575],
       [ 0.84249714, -0.40045738, -0.36032271],
       [ 0.02505282,  0.69727615, -0.71636466]])

In [ ]:
# PC1=0.54HV+0.59icmed+0.59icavg
#PC1 +VELY CORR WITH HV

In [ ]:
# Only keep PCs with eigenvalue>=1
# Use PC1 to replace HV, icmed, and icavg
pca2 = PCA(n_components=1)
PCA_v2 = pca2.fit_transform(x3_PCA)

In [ ]:
# Obtain the PC1
pcaDf = pd.DataFrame(data = PCA_v2
             , columns = ['PC1'])
x3_model = pd.concat([x3_no_PCA,pcaDf],axis=1)
x3_model.head()

zip  homeowner     child    gender    wealth       num       max  \
0 -0.651531   0.546239 -0.199149  0.800776  1.022912  1.096731 -0.479362   
1 -1.501355   0.546239 -0.199149 -1.248789  0.235377 -0.136017 -0.209334   
2  1.048116  -1.830701  2.677454  0.800776  0.629144 -0.752391 -0.299343   
3  1.048116   0.546239 -0.199149 -1.248789 -0.945925  1.977265 -0.299343   
4 -0.651531   0.546239 -0.199149 -1.248789  0.629144 -1.280711 -0.254339   

     totalm       PC1  
0 -0.517113  1.964982  
1  0.692870 -0.026007  
2 -0.517113 -0.481403  
3 -0.275116  0.921688  
4 -0.275116 -0.345861

In [ ]:
#pc1=pc for hv,icmed,icavg
#captures 88% of info

In [ ]:
# Data partition: the independent variables are just four PCs
x3_train, x3_val, y_train, y_val = train_test_split(x3_model,y, test_size=0.3,
                                                    random_state=0)

In [ ]:
#MODEL 3 CONSTRUCTION
model3 = LogisticRegression()
model3.fit(x3_train,y_train)
# Evaluating accuracy
model3.score(x3_val,y_val)

0.6591880341880342

In [ ]:
#accuracy dropped a bit but there are advantages
#1 makes more sense
#2 easier to explain the result

In [ ]:
#Take a look at model estimation
# Show model coefficients
import numpy as np
pd.DataFrame(zip(x3_train.columns, np.transpose(model3.coef_)),
             columns=['features', 'coef'])

features                     coef
0        zip    [0.03756174403452693]
1  homeowner     [0.1034938038229797]
2      child   [-0.06545205738229305]
3     gender     [0.4253941818615116]
4     wealth  [-0.026281631150054524]
5        num   [0.021961746651610967]
6        max   [0.053094264956110686]
7     totalm    [-0.3524770482418666]
8        PC1  [-0.022941420354505967]

In [ ]:
#what can we see from here about people's intent to donate?
# PC1=0.54HV+0.59icmed+0.59icavg
# PC1 is theoretically related to the financial status of the neighbourhood
# above we have -ve corr
#i.e HIGHER PC1 LOWER POSSIBILITY TO BECOME A DONOR(Rich people less likely to become a donor)